### ISSUE TITLE
nextcloud_announcements Symfony Component Routing Exception

### ISSUE THREAD

**Issue by akurzawa** [nextcloud/nextcloud_announcements#60] opened 2019-10-30 11:54 UTC
Hi

Nextcloud 17 fresh install from c-raiget script, debian 9.9
https://github.com/criegerde/install-nextcloud/blob/master/install-nextcloud-mariadb-debian.sh

The same issue like here:
https://github.com/nextcloud/nextcloud_announcements/issues/54

**When** the Announcement center app is disabled there is no error.

Error in log:
```
[no app in context] Error: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "ocs.provisioning_api.AppsController.disable" as such route does not exist. at <<closure>>

 0. /var/www/nextcloud/lib/private/Route/Router.php line 337
    Symfony\Component\Routing\Generator\UrlGenerator->generate("ocs.provisionin ... e", {app: "nextcloud_announcements"}, 1)
 1. /var/www/nextcloud/lib/private/Route/CachingRouter.php line 60
    OC\Route\Router->generate("ocs.provisionin ... e", {app: "nextcloud_announcements"}, false)
 2. /var/www/nextcloud/lib/private/URLGenerator.php line 95
    OC\Route\CachingRouter->generate("ocs.provisionin ... e", {app: "nextcloud_announcements"}, false)
 3. /var/www/nextcloud/apps/nextcloud_announcements/lib/Notification/Notifier.php line 116
    OC\URLGenerator->linkToOCSRouteAbsolute("provisioning_api.AppsController.disable", {app: "nextcloud_announcements"})
 4. /var/www/nextcloud/lib/private/Notification/Manager.php line 253
    OCA\NextcloudAnnouncements\Notification\Notifier->prepare(OC\Notification\Notification {}, "pl")
 5. /var/www/nextcloud/apps/notifications/lib/Controller/EndpointController.php line 102
    OC\Notification\Manager->prepare(OC\Notification\Notification {}, "pl")
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Notifications\Controller\EndpointController->listNotifications("v2")
 7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Notification ... {}, "listNotifications")
 8. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notification ... {}, "listNotifications")
 9. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Notificati ... r", "listNotifications", OC\AppFramework\ ... {}, {apiVersion: "v2 ... "})
10. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({apiVersion: "v2 ... "})
11. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {apiVersion: "v2 ... "})
12. /var/www/nextcloud/ocs/v1.php line 82
    OC\Route\Router->match("/ocsapp/apps/no ... s")
13. /var/www/nextcloud/ocs/v2.php line 24
    undefinedundefinedrequire_once("/var/www/nextcloud/ocs/v1.php")

GET /ocs/v2.php/apps/notifications/api/v2/notifications
from 10.0.0.11 by jupiter at 2019-10-30T12:49:33+01:00
```

**Comment by nickvergessen** [comment] 2019-10-30 20:40
Duplicate of #54

**Closed by nickvergessen** 2019-10-30 20:40 UTC
